import type { AppState } from "./types";

export const DEFAULT_STATE: AppState = {
  profile: null,
  schedule: null,
  savedExercises: [],
  logs: [],
  checkIns: [],
  weights: [],
  measurements: [],
  foodLog: [],
  completedDates: [],
  programs: [],
  activeProgramId: null,
  sessions: [],
  activeSessionId: null,
  water: [],
  waterTargetMl: 3000,
  hydrationAlertsEnabled: true,
  manualPRs: {},
  units: "kg",
  remindersEnabled: true,
  autoShareWorkouts: false,
  deviceRemindersEnabled: false,
  workoutReminderHour: 18,
  workoutReminderMinute: 0,
  streakArmor: { shields: 0, lastRefillMonth: "", usedDates: [] },
  healthSync: { enabled: false, importWorkouts: true, exportWorkouts: true },
};
