import type { Exercise } from "./types";

export const EXERCISES: Exercise[] = [
  // CHEST
  {
    id: "bench-press",
    name: "Bench Press",
    muscleGroup: "CHEST",
    equipment: ["FULL_GYM"],
    skill: "INTERMEDIATE",
    sets: 4,
    reps: "6-8",
    videoId: "rT7DgCr-3pg",
    instruction: "Lower the bar to mid-chest, drive feet, press straight up.",
  },
  {
    id: "incline-db-press",
    name: "Incline Dumbbell Press",
    muscleGroup: "CHEST",
    equipment: ["FULL_GYM", "HOME_GYM"],
    skill: "BEGINNER",
    sets: 3,
    reps: "8-10",
    videoId: "8iPEnn-ltC8",
    instruction: "Bench at 30°, press dumbbells up and slightly in.",
  },
  {
    id: "cable-fly",
    name: "Cable Fly",
    muscleGroup: "CHEST",
    equipment: ["FULL_GYM"],
    skill: "INTERMEDIATE",
    sets: 3,
    reps: "10-12",
    videoId: "Iwe6AmxVf7o",
    instruction: "Slight bend in elbows, squeeze chest at center.",
  },
  {
    id: "dips",
    name: "Dips",
    muscleGroup: "CHEST",
    equipment: ["FULL_GYM", "HOME_GYM", "BODYWEIGHT"],
    skill: "INTERMEDIATE",
    sets: 3,
    reps: "8-12",
    videoId: "2z8JmcrW-As",
    instruction: "Lean forward for chest, lower until shoulders below elbows.",
  },
  {
    id: "push-ups",
    name: "Push Ups",
    muscleGroup: "CHEST",
    equipment: ["BODYWEIGHT", "HOME_GYM", "FULL_GYM"],
    skill: "BEGINNER",
    sets: 3,
    reps: "12-20",
    videoId: "IODxDxX7oi4",
    instruction: "Body rigid, lower chest to floor, press fully up.",
  },
  {
    id: "close-grip-push-up",
    name: "Close-Grip Push Up",
    muscleGroup: "ARMS",
    equipment: ["BODYWEIGHT", "HOME_GYM", "FULL_GYM"],
    skill: "BEGINNER",
    sets: 3,
    reps: "8-15",
    videoId: "",
    youtubeQuery: "close grip push up proper form",
    instruction: "Keep hands just inside shoulder width and elbows close as you press.",
  },

  // BACK
  {
    id: "deadlift",
    name: "Deadlift",
    muscleGroup: "BACK",
    equipment: ["FULL_GYM"],
    skill: "ADVANCED",
    sets: 4,
    reps: "3-5",
    videoId: "op9kVnSso6Q",
    instruction: "Brace core, hinge, drive floor away, lock out hips.",
  },
  {
    id: "pull-ups",
    name: "Pull Ups",
    muscleGroup: "BACK",
    equipment: ["FULL_GYM", "HOME_GYM", "BODYWEIGHT"],
    skill: "INTERMEDIATE",
    sets: 4,
    reps: "6-10",
    videoId: "eGo4IYlbE5g",
    instruction: "Pull chest to bar, control descent fully.",
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    muscleGroup: "BACK",
    equipment: ["FULL_GYM"],
    skill: "BEGINNER",
    sets: 3,
    reps: "10-12",
    videoId: "CAwf7n6Luuc",
    instruction: "Pull bar to upper chest, squeeze lats.",
  },
  {
    id: "seated-row",
    name: "Seated Row",
    muscleGroup: "BACK",
    equipment: ["FULL_GYM"],
    skill: "BEGINNER",
    sets: 3,
    reps: "8-12",
    videoId: "GZbfZ033f74",
    instruction: "Pull handle to lower chest, squeeze shoulder blades.",
  },
  {
    id: "face-pull",
    name: "Face Pull",
    muscleGroup: "BACK",
    equipment: ["FULL_GYM"],
    skill: "BEGINNER",
    sets: 3,
    reps: "12-15",
    videoId: "rep-qVOkqgk",
    instruction: "Pull rope to forehead, elbows high, externally rotate.",
  },
  {
    id: "inverted-row",
    name: "Inverted Row",
    muscleGroup: "BACK",
    equipment: ["FULL_GYM", "HOME_GYM", "BODYWEIGHT"],
    skill: "BEGINNER",
    sets: 3,
    reps: "8-15",
    videoId: "",
    youtubeQuery: "inverted row proper form",
    instruction: "Keep your body rigid and pull your chest toward the bar or sturdy support.",
  },
  {
    id: "superman",
    name: "Superman",
    muscleGroup: "BACK",
    equipment: ["FULL_GYM", "HOME_GYM", "BODYWEIGHT"],
    skill: "BEGINNER",
    sets: 3,
    reps: "10-15",
    videoId: "",
    youtubeQuery: "superman exercise proper form",
    instruction: "Lift arms and legs gently, pause, then lower without overextending your back.",
  },

  // LEGS
  {
    id: "squat",
    name: "Back Squat",
    muscleGroup: "LEGS",
    equipment: ["FULL_GYM"],
    skill: "INTERMEDIATE",
    sets: 4,
    reps: "6-8",
    videoId: "ultWZbUMPL8",
    instruction: "Brace, break at hips and knees, depth at parallel or below.",
  },
  {
    id: "rdl",
    name: "Romanian Deadlift",
    muscleGroup: "LEGS",
    equipment: ["FULL_GYM", "HOME_GYM"],
    skill: "INTERMEDIATE",
    sets: 3,
    reps: "8-10",
    videoId: "JCXUYuzwNrM",
    instruction: "Soft knees, hinge hips, feel hamstring stretch.",
  },
  {
    id: "leg-press",
    name: "Leg Press",
    muscleGroup: "LEGS",
    equipment: ["FULL_GYM"],
    skill: "BEGINNER",
    sets: 3,
    reps: "10-12",
    videoId: "IZxyjW7MPJQ",
    instruction: "Feet shoulder-width, lower under control, do not lock knees.",
  },
  {
    id: "lunges",
    name: "Walking Lunges",
    muscleGroup: "LEGS",
    equipment: ["FULL_GYM", "HOME_GYM", "BODYWEIGHT"],
    skill: "BEGINNER",
    sets: 3,
    reps: "10/leg",
    videoId: "L8fvypPrzzs",
    instruction: "Step forward, drop back knee toward floor, drive up.",
  },
  {
    id: "leg-curl",
    name: "Leg Curl",
    muscleGroup: "LEGS",
    equipment: ["FULL_GYM"],
    skill: "BEGINNER",
    sets: 3,
    reps: "10-12",
    videoId: "1Tq3QdYUuHs",
    instruction: "Curl heels to glutes, squeeze hamstrings hard.",
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    muscleGroup: "LEGS",
    equipment: ["FULL_GYM", "HOME_GYM"],
    skill: "BEGINNER",
    sets: 3,
    reps: "8-12",
    videoId: "",
    youtubeQuery: "goblet squat proper form",
    instruction: "Hold one weight at your chest, brace, and sit between your hips.",
  },
  {
    id: "bodyweight-squat",
    name: "Bodyweight Squat",
    muscleGroup: "LEGS",
    equipment: ["FULL_GYM", "HOME_GYM", "BODYWEIGHT"],
    skill: "BEGINNER",
    sets: 3,
    reps: "12-20",
    videoId: "",
    youtubeQuery: "bodyweight squat proper form",
    instruction: "Brace your trunk, sit between your hips, and keep your whole foot planted.",
  },
  {
    id: "split-squat",
    name: "Split Squat",
    muscleGroup: "LEGS",
    equipment: ["FULL_GYM", "HOME_GYM", "BODYWEIGHT"],
    skill: "BEGINNER",
    sets: 3,
    reps: "8-12/leg",
    videoId: "",
    youtubeQuery: "bodyweight split squat proper form",
    instruction: "Use a stable stance, lower the back knee, and drive through the front foot.",
  },
  {
    id: "glute-bridge",
    name: "Glute Bridge",
    muscleGroup: "LEGS",
    equipment: ["FULL_GYM", "HOME_GYM", "BODYWEIGHT"],
    skill: "BEGINNER",
    sets: 3,
    reps: "12-20",
    videoId: "",
    youtubeQuery: "glute bridge proper form",
    instruction: "Brace your ribs down and squeeze your glutes to reach full hip extension.",
  },
  {
    id: "calf-raise",
    name: "Standing Calf Raise",
    muscleGroup: "LEGS",
    equipment: ["FULL_GYM", "HOME_GYM", "BODYWEIGHT"],
    skill: "BEGINNER",
    sets: 3,
    reps: "12-20",
    videoId: "",
    youtubeQuery: "standing calf raise proper form",
    instruction: "Rise onto the balls of your feet, pause at the top, and lower under control.",
  },

  // SHOULDERS
  {
    id: "ohp",
    name: "Overhead Press",
    muscleGroup: "SHOULDERS",
    equipment: ["FULL_GYM", "HOME_GYM"],
    skill: "INTERMEDIATE",
    sets: 4,
    reps: "6-8",
    videoId: "2yjwXTZQDDI",
    instruction: "Brace core, press bar overhead, finish with biceps by ears.",
  },
  {
    id: "lateral-raise",
    name: "Lateral Raise",
    muscleGroup: "SHOULDERS",
    equipment: ["FULL_GYM", "HOME_GYM"],
    skill: "BEGINNER",
    sets: 3,
    reps: "12-15",
    videoId: "3VcKaXpzqRo",
    instruction: "Lead with elbows, raise to shoulder height, no swing.",
  },
  {
    id: "front-raise",
    name: "Front Raise",
    muscleGroup: "SHOULDERS",
    equipment: ["FULL_GYM", "HOME_GYM"],
    skill: "BEGINNER",
    sets: 3,
    reps: "10-12",
    videoId: "-t7fuZ0KhDA",
    instruction: "Raise dumbbells in front to shoulder height, controlled.",
  },
  {
    id: "rear-delt-fly",
    name: "Rear Delt Fly",
    muscleGroup: "SHOULDERS",
    equipment: ["FULL_GYM", "HOME_GYM"],
    skill: "BEGINNER",
    sets: 3,
    reps: "12-15",
    videoId: "EA7u4Q_8HQ0",
    instruction: "Hinge forward, raise arms out to sides, squeeze rear delts.",
  },
  {
    id: "pike-push-up",
    name: "Pike Push Up",
    muscleGroup: "SHOULDERS",
    equipment: ["FULL_GYM", "HOME_GYM", "BODYWEIGHT"],
    skill: "INTERMEDIATE",
    sets: 3,
    reps: "6-12",
    videoId: "",
    youtubeQuery: "pike push up proper form",
    instruction: "Keep hips high and lower your head forward between your hands before pressing.",
  },

  // ARMS
  {
    id: "barbell-curl",
    name: "Barbell Curl",
    muscleGroup: "ARMS",
    equipment: ["FULL_GYM", "HOME_GYM"],
    skill: "BEGINNER",
    sets: 3,
    reps: "8-12",
    videoId: "kwG2ipFRgfo",
    instruction: "Elbows locked at sides, curl bar without swinging torso.",
  },
  {
    id: "hammer-curl",
    name: "Hammer Curl",
    muscleGroup: "ARMS",
    equipment: ["FULL_GYM", "HOME_GYM"],
    skill: "BEGINNER",
    sets: 3,
    reps: "10-12",
    videoId: "zC3nLlEvin4",
    instruction: "Neutral grip, curl dumbbells, target brachialis.",
  },
  {
    id: "skull-crushers",
    name: "Skull Crushers",
    muscleGroup: "ARMS",
    equipment: ["FULL_GYM", "HOME_GYM"],
    skill: "INTERMEDIATE",
    sets: 3,
    reps: "8-12",
    videoId: "d_KZxkY_0cM",
    instruction: "Lower bar to forehead, elbows tucked, extend fully.",
  },
  {
    id: "tricep-pushdown",
    name: "Tricep Pushdown",
    muscleGroup: "ARMS",
    equipment: ["FULL_GYM"],
    skill: "BEGINNER",
    sets: 3,
    reps: "10-15",
    videoId: "2-LAMcpzODU",
    instruction: "Elbows pinned, press cable down, full lockout.",
  },

  // CORE
  {
    id: "plank",
    name: "Plank",
    muscleGroup: "CORE",
    equipment: ["BODYWEIGHT", "HOME_GYM", "FULL_GYM"],
    skill: "BEGINNER",
    sets: 3,
    reps: "45-60s",
    videoId: "ASdvN_XEl_c",
    instruction: "Forearms down, body straight, brace abs & glutes.",
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    muscleGroup: "CORE",
    equipment: ["FULL_GYM", "HOME_GYM"],
    skill: "INTERMEDIATE",
    sets: 3,
    reps: "8-12",
    videoId: "Pr1ieGZ5atk",
    instruction: "Hang, raise legs to 90°, control descent.",
  },
  {
    id: "cable-crunch",
    name: "Cable Crunch",
    muscleGroup: "CORE",
    equipment: ["FULL_GYM"],
    skill: "BEGINNER",
    sets: 3,
    reps: "12-15",
    videoId: "6GMKPQVERzw",
    instruction: "Kneel, crunch elbows to thighs, contract abs hard.",
  },
  {
    id: "ab-wheel",
    name: "Ab Wheel Rollout",
    muscleGroup: "CORE",
    equipment: ["HOME_GYM", "FULL_GYM"],
    skill: "ADVANCED",
    sets: 3,
    reps: "6-10",
    videoId: "rqiTPdK1c_I",
    instruction: "Roll out controlled, keep back flat, pull back in.",
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    muscleGroup: "CORE",
    equipment: ["BODYWEIGHT", "HOME_GYM", "FULL_GYM"],
    skill: "BEGINNER",
    sets: 3,
    reps: "8-12/side",
    videoId: "",
    youtubeQuery: "dead bug exercise proper form",
    instruction: "Press your lower back down and extend opposite limbs without losing position.",
  },
  {
    id: "bicycle-crunch",
    name: "Bicycle Crunch",
    muscleGroup: "CORE",
    equipment: ["BODYWEIGHT", "HOME_GYM", "FULL_GYM"],
    skill: "BEGINNER",
    sets: 3,
    reps: "12-20/side",
    videoId: "",
    youtubeQuery: "bicycle crunch proper form",
    instruction: "Rotate your ribs toward the opposite knee without pulling on your neck.",
  },
];

export function getExercise(id: string, saved: Exercise[] = []) {
  return (
    saved.find((exercise) => exercise.id === id) ?? EXERCISES.find((exercise) => exercise.id === id)
  );
}

export function allExercises(saved: Exercise[] = []) {
  const byId = new Map(EXERCISES.map((exercise) => [exercise.id, exercise]));
  for (const exercise of saved) byId.set(exercise.id, exercise);
  return [...byId.values()];
}
