/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutTrackerRouteImport } from './routes/workout-tracker'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as TiktokRouteImport } from './routes/tiktok'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StopGuessingRouteImport } from './routes/stop-guessing'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as RealWeekRouteImport } from './routes/real-week'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as R3DayGymPlanRouteImport } from './routes/3-day-gym-plan'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutLiveRouteImport } from './routes/workout.live'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as TabsTrainRouteImport } from './routes/_tabs.train'
import { Route as TabsStrengthRouteImport } from './routes/_tabs.strength'
import { Route as TabsProgressRouteImport } from './routes/_tabs.progress'
import { Route as TabsProgramsRouteImport } from './routes/_tabs.programs'
import { Route as TabsProfileRouteImport } from './routes/_tabs.profile'
import { Route as TabsPlanRouteImport } from './routes/_tabs.plan'
import { Route as TabsLibraryRouteImport } from './routes/_tabs.library'
import { Route as TabsFriendsRouteImport } from './routes/_tabs.friends'
import { Route as TabsDietRouteImport } from './routes/_tabs.diet'
import { Route as TabsChallengesRouteImport } from './routes/_tabs.challenges'
import { Route as TabsCatalogueRouteImport } from './routes/_tabs.catalogue'
import { Route as TabsProgramsProgramIdRouteImport } from './routes/_tabs.programs.$programId'
import { Route as TabsLiftExerciseIdRouteImport } from './routes/_tabs.lift.$exerciseId'
import { Route as TabsAthleteIdRouteImport } from './routes/_tabs.athlete.$id'

const WorkoutTrackerRoute = WorkoutTrackerRouteImport.update({
  id: '/workout-tracker',
  path: '/workout-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokRoute = TiktokRouteImport.update({
  id: '/tiktok',
  path: '/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StopGuessingRoute = StopGuessingRouteImport.update({
  id: '/stop-guessing',
  path: '/stop-guessing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const RealWeekRoute = RealWeekRouteImport.update({
  id: '/real-week',
  path: '/real-week',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const R3DayGymPlanRoute = R3DayGymPlanRouteImport.update({
  id: '/3-day-gym-plan',
  path: '/3-day-gym-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutLiveRoute = WorkoutLiveRouteImport.update({
  id: '/workout/live',
  path: '/workout/live',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsTrainRoute = TabsTrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => TabsRoute,
} as any)
const TabsStrengthRoute = TabsStrengthRouteImport.update({
  id: '/strength',
  path: '/strength',
  getParentRoute: () => TabsRoute,
} as any)
const TabsProgressRoute = TabsProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => TabsRoute,
} as any)
const TabsProgramsRoute = TabsProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => TabsRoute,
} as any)
const TabsProfileRoute = TabsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TabsRoute,
} as any)
const TabsPlanRoute = TabsPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => TabsRoute,
} as any)
const TabsLibraryRoute = TabsLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => TabsRoute,
} as any)
const TabsFriendsRoute = TabsFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => TabsRoute,
} as any)
const TabsDietRoute = TabsDietRouteImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => TabsRoute,
} as any)
const TabsChallengesRoute = TabsChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => TabsRoute,
} as any)
const TabsCatalogueRoute = TabsCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => TabsRoute,
} as any)
const TabsProgramsProgramIdRoute = TabsProgramsProgramIdRouteImport.update({
  id: '/$programId',
  path: '/$programId',
  getParentRoute: () => TabsProgramsRoute,
} as any)
const TabsLiftExerciseIdRoute = TabsLiftExerciseIdRouteImport.update({
  id: '/lift/$exerciseId',
  path: '/lift/$exerciseId',
  getParentRoute: () => TabsRoute,
} as any)
const TabsAthleteIdRoute = TabsAthleteIdRouteImport.update({
  id: '/athlete/$id',
  path: '/athlete/$id',
  getParentRoute: () => TabsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/3-day-gym-plan': typeof R3DayGymPlanRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/creator': typeof CreatorRoute
  '/disclaimer': typeof DisclaimerRoute
  '/guide': typeof GuideRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/real-week': typeof RealWeekRoute
  '/recovery': typeof RecoveryRoute
  '/settings': typeof SettingsRoute
  '/stop-guessing': typeof StopGuessingRoute
  '/terms': typeof TermsRoute
  '/tiktok': typeof TiktokRoute
  '/upgrade': typeof UpgradeRoute
  '/workout-tracker': typeof WorkoutTrackerRoute
  '/catalogue': typeof TabsCatalogueRoute
  '/challenges': typeof TabsChallengesRoute
  '/diet': typeof TabsDietRoute
  '/friends': typeof TabsFriendsRoute
  '/library': typeof TabsLibraryRoute
  '/plan': typeof TabsPlanRoute
  '/profile': typeof TabsProfileRoute
  '/programs': typeof TabsProgramsRouteWithChildren
  '/progress': typeof TabsProgressRoute
  '/strength': typeof TabsStrengthRoute
  '/train': typeof TabsTrainRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/workout/live': typeof WorkoutLiveRoute
  '/athlete/$id': typeof TabsAthleteIdRoute
  '/lift/$exerciseId': typeof TabsLiftExerciseIdRoute
  '/programs/$programId': typeof TabsProgramsProgramIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/3-day-gym-plan': typeof R3DayGymPlanRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/creator': typeof CreatorRoute
  '/disclaimer': typeof DisclaimerRoute
  '/guide': typeof GuideRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/real-week': typeof RealWeekRoute
  '/recovery': typeof RecoveryRoute
  '/settings': typeof SettingsRoute
  '/stop-guessing': typeof StopGuessingRoute
  '/terms': typeof TermsRoute
  '/tiktok': typeof TiktokRoute
  '/upgrade': typeof UpgradeRoute
  '/workout-tracker': typeof WorkoutTrackerRoute
  '/catalogue': typeof TabsCatalogueRoute
  '/challenges': typeof TabsChallengesRoute
  '/diet': typeof TabsDietRoute
  '/friends': typeof TabsFriendsRoute
  '/library': typeof TabsLibraryRoute
  '/plan': typeof TabsPlanRoute
  '/profile': typeof TabsProfileRoute
  '/programs': typeof TabsProgramsRouteWithChildren
  '/progress': typeof TabsProgressRoute
  '/strength': typeof TabsStrengthRoute
  '/train': typeof TabsTrainRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/workout/live': typeof WorkoutLiveRoute
  '/athlete/$id': typeof TabsAthleteIdRoute
  '/lift/$exerciseId': typeof TabsLiftExerciseIdRoute
  '/programs/$programId': typeof TabsProgramsProgramIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/3-day-gym-plan': typeof R3DayGymPlanRoute
  '/_tabs': typeof TabsRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/creator': typeof CreatorRoute
  '/disclaimer': typeof DisclaimerRoute
  '/guide': typeof GuideRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/real-week': typeof RealWeekRoute
  '/recovery': typeof RecoveryRoute
  '/settings': typeof SettingsRoute
  '/stop-guessing': typeof StopGuessingRoute
  '/terms': typeof TermsRoute
  '/tiktok': typeof TiktokRoute
  '/upgrade': typeof UpgradeRoute
  '/workout-tracker': typeof WorkoutTrackerRoute
  '/_tabs/catalogue': typeof TabsCatalogueRoute
  '/_tabs/challenges': typeof TabsChallengesRoute
  '/_tabs/diet': typeof TabsDietRoute
  '/_tabs/friends': typeof TabsFriendsRoute
  '/_tabs/library': typeof TabsLibraryRoute
  '/_tabs/plan': typeof TabsPlanRoute
  '/_tabs/profile': typeof TabsProfileRoute
  '/_tabs/programs': typeof TabsProgramsRouteWithChildren
  '/_tabs/progress': typeof TabsProgressRoute
  '/_tabs/strength': typeof TabsStrengthRoute
  '/_tabs/train': typeof TabsTrainRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/workout/live': typeof WorkoutLiveRoute
  '/_tabs/athlete/$id': typeof TabsAthleteIdRoute
  '/_tabs/lift/$exerciseId': typeof TabsLiftExerciseIdRoute
  '/_tabs/programs/$programId': typeof TabsProgramsProgramIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/3-day-gym-plan'
    | '/admin'
    | '/auth'
    | '/creator'
    | '/disclaimer'
    | '/guide'
    | '/leaderboard'
    | '/onboarding'
    | '/privacy'
    | '/real-week'
    | '/recovery'
    | '/settings'
    | '/stop-guessing'
    | '/terms'
    | '/tiktok'
    | '/upgrade'
    | '/workout-tracker'
    | '/catalogue'
    | '/challenges'
    | '/diet'
    | '/friends'
    | '/library'
    | '/plan'
    | '/profile'
    | '/programs'
    | '/progress'
    | '/strength'
    | '/train'
    | '/checkout/return'
    | '/workout/live'
    | '/athlete/$id'
    | '/lift/$exerciseId'
    | '/programs/$programId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/3-day-gym-plan'
    | '/admin'
    | '/auth'
    | '/creator'
    | '/disclaimer'
    | '/guide'
    | '/leaderboard'
    | '/onboarding'
    | '/privacy'
    | '/real-week'
    | '/recovery'
    | '/settings'
    | '/stop-guessing'
    | '/terms'
    | '/tiktok'
    | '/upgrade'
    | '/workout-tracker'
    | '/catalogue'
    | '/challenges'
    | '/diet'
    | '/friends'
    | '/library'
    | '/plan'
    | '/profile'
    | '/programs'
    | '/progress'
    | '/strength'
    | '/train'
    | '/checkout/return'
    | '/workout/live'
    | '/athlete/$id'
    | '/lift/$exerciseId'
    | '/programs/$programId'
  id:
    | '__root__'
    | '/'
    | '/3-day-gym-plan'
    | '/_tabs'
    | '/admin'
    | '/auth'
    | '/creator'
    | '/disclaimer'
    | '/guide'
    | '/leaderboard'
    | '/onboarding'
    | '/privacy'
    | '/real-week'
    | '/recovery'
    | '/settings'
    | '/stop-guessing'
    | '/terms'
    | '/tiktok'
    | '/upgrade'
    | '/workout-tracker'
    | '/_tabs/catalogue'
    | '/_tabs/challenges'
    | '/_tabs/diet'
    | '/_tabs/friends'
    | '/_tabs/library'
    | '/_tabs/plan'
    | '/_tabs/profile'
    | '/_tabs/programs'
    | '/_tabs/progress'
    | '/_tabs/strength'
    | '/_tabs/train'
    | '/checkout/return'
    | '/workout/live'
    | '/_tabs/athlete/$id'
    | '/_tabs/lift/$exerciseId'
    | '/_tabs/programs/$programId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R3DayGymPlanRoute: typeof R3DayGymPlanRoute
  TabsRoute: typeof TabsRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CreatorRoute: typeof CreatorRoute
  DisclaimerRoute: typeof DisclaimerRoute
  GuideRoute: typeof GuideRoute
  LeaderboardRoute: typeof LeaderboardRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  RealWeekRoute: typeof RealWeekRoute
  RecoveryRoute: typeof RecoveryRoute
  SettingsRoute: typeof SettingsRoute
  StopGuessingRoute: typeof StopGuessingRoute
  TermsRoute: typeof TermsRoute
  TiktokRoute: typeof TiktokRoute
  UpgradeRoute: typeof UpgradeRoute
  WorkoutTrackerRoute: typeof WorkoutTrackerRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  WorkoutLiveRoute: typeof WorkoutLiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workout-tracker': {
      id: '/workout-tracker'
      path: '/workout-tracker'
      fullPath: '/workout-tracker'
      preLoaderRoute: typeof WorkoutTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok': {
      id: '/tiktok'
      path: '/tiktok'
      fullPath: '/tiktok'
      preLoaderRoute: typeof TiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stop-guessing': {
      id: '/stop-guessing'
      path: '/stop-guessing'
      fullPath: '/stop-guessing'
      preLoaderRoute: typeof StopGuessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-week': {
      id: '/real-week'
      path: '/real-week'
      fullPath: '/real-week'
      preLoaderRoute: typeof RealWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3-day-gym-plan': {
      id: '/3-day-gym-plan'
      path: '/3-day-gym-plan'
      fullPath: '/3-day-gym-plan'
      preLoaderRoute: typeof R3DayGymPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/live': {
      id: '/workout/live'
      path: '/workout/live'
      fullPath: '/workout/live'
      preLoaderRoute: typeof WorkoutLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/train': {
      id: '/_tabs/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TabsTrainRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/strength': {
      id: '/_tabs/strength'
      path: '/strength'
      fullPath: '/strength'
      preLoaderRoute: typeof TabsStrengthRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/progress': {
      id: '/_tabs/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof TabsProgressRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/programs': {
      id: '/_tabs/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof TabsProgramsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/profile': {
      id: '/_tabs/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof TabsProfileRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/plan': {
      id: '/_tabs/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof TabsPlanRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/library': {
      id: '/_tabs/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof TabsLibraryRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/friends': {
      id: '/_tabs/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof TabsFriendsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/diet': {
      id: '/_tabs/diet'
      path: '/diet'
      fullPath: '/diet'
      preLoaderRoute: typeof TabsDietRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/challenges': {
      id: '/_tabs/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof TabsChallengesRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/catalogue': {
      id: '/_tabs/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof TabsCatalogueRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/programs/$programId': {
      id: '/_tabs/programs/$programId'
      path: '/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof TabsProgramsProgramIdRouteImport
      parentRoute: typeof TabsProgramsRoute
    }
    '/_tabs/lift/$exerciseId': {
      id: '/_tabs/lift/$exerciseId'
      path: '/lift/$exerciseId'
      fullPath: '/lift/$exerciseId'
      preLoaderRoute: typeof TabsLiftExerciseIdRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/athlete/$id': {
      id: '/_tabs/athlete/$id'
      path: '/athlete/$id'
      fullPath: '/athlete/$id'
      preLoaderRoute: typeof TabsAthleteIdRouteImport
      parentRoute: typeof TabsRoute
    }
  }
}

interface TabsProgramsRouteChildren {
  TabsProgramsProgramIdRoute: typeof TabsProgramsProgramIdRoute
}

const TabsProgramsRouteChildren: TabsProgramsRouteChildren = {
  TabsProgramsProgramIdRoute: TabsProgramsProgramIdRoute,
}

const TabsProgramsRouteWithChildren = TabsProgramsRoute._addFileChildren(
  TabsProgramsRouteChildren,
)

interface TabsRouteChildren {
  TabsCatalogueRoute: typeof TabsCatalogueRoute
  TabsChallengesRoute: typeof TabsChallengesRoute
  TabsDietRoute: typeof TabsDietRoute
  TabsFriendsRoute: typeof TabsFriendsRoute
  TabsLibraryRoute: typeof TabsLibraryRoute
  TabsPlanRoute: typeof TabsPlanRoute
  TabsProfileRoute: typeof TabsProfileRoute
  TabsProgramsRoute: typeof TabsProgramsRouteWithChildren
  TabsProgressRoute: typeof TabsProgressRoute
  TabsStrengthRoute: typeof TabsStrengthRoute
  TabsTrainRoute: typeof TabsTrainRoute
  TabsAthleteIdRoute: typeof TabsAthleteIdRoute
  TabsLiftExerciseIdRoute: typeof TabsLiftExerciseIdRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsCatalogueRoute: TabsCatalogueRoute,
  TabsChallengesRoute: TabsChallengesRoute,
  TabsDietRoute: TabsDietRoute,
  TabsFriendsRoute: TabsFriendsRoute,
  TabsLibraryRoute: TabsLibraryRoute,
  TabsPlanRoute: TabsPlanRoute,
  TabsProfileRoute: TabsProfileRoute,
  TabsProgramsRoute: TabsProgramsRouteWithChildren,
  TabsProgressRoute: TabsProgressRoute,
  TabsStrengthRoute: TabsStrengthRoute,
  TabsTrainRoute: TabsTrainRoute,
  TabsAthleteIdRoute: TabsAthleteIdRoute,
  TabsLiftExerciseIdRoute: TabsLiftExerciseIdRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R3DayGymPlanRoute: R3DayGymPlanRoute,
  TabsRoute: TabsRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CreatorRoute: CreatorRoute,
  DisclaimerRoute: DisclaimerRoute,
  GuideRoute: GuideRoute,
  LeaderboardRoute: LeaderboardRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  RealWeekRoute: RealWeekRoute,
  RecoveryRoute: RecoveryRoute,
  SettingsRoute: SettingsRoute,
  StopGuessingRoute: StopGuessingRoute,
  TermsRoute: TermsRoute,
  TiktokRoute: TiktokRoute,
  UpgradeRoute: UpgradeRoute,
  WorkoutTrackerRoute: WorkoutTrackerRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  WorkoutLiveRoute: WorkoutLiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
