// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SESSION_BACKUP_KEY = 'deadset_auth_session_v1';

type SessionBackup = { access_token: string; refresh_token: string };

export function saveSessionBackup(session: SessionBackup) {
  if (typeof window === 'undefined') return;
  localStorage.setItem(SESSION_BACKUP_KEY, JSON.stringify({
    access_token: session.access_token,
    refresh_token: session.refresh_token,
  }));
}

function clearSessionBackup() {
  if (typeof window !== 'undefined') localStorage.removeItem(SESSION_BACKUP_KEY);
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
    }
  });

  client.auth.onAuthStateChange((event, session) => {
    if (session) saveSessionBackup(session);
    else if (event === 'SIGNED_OUT') clearSessionBackup();
  });

  return client;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

export async function restoreSupabaseSession() {
  if (typeof window === 'undefined') return;
  const { data: { session } } = await supabase.auth.getSession();
  if (session) {
    saveSessionBackup(session);
    return;
  }
  const raw = localStorage.getItem(SESSION_BACKUP_KEY);
  if (!raw) return;
  try {
    const saved = JSON.parse(raw) as Partial<SessionBackup>;
    if (!saved.access_token || !saved.refresh_token) throw new Error('Invalid session backup');
    const { error } = await supabase.auth.setSession({
      access_token: saved.access_token,
      refresh_token: saved.refresh_token,
    });
    if (error) throw error;
  } catch {
    clearSessionBackup();
  }
}
