// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SESSION_BACKUP_KEY = "deadset_auth_session_v1";
const SESSION_COOKIE_ACCESS = "deadset_at";
const SESSION_COOKIE_REFRESH = "deadset_rt";
const SUPABASE_COOKIE_PREFIX = "deadset_sb_";
const COOKIE_MAX_AGE_SECONDS = 60 * 60 * 24 * 180; // 6 months

type SessionBackup = { access_token: string; refresh_token: string };

function isBrowser() {
  return typeof window !== "undefined";
}

function cookieAttributes(maxAge = COOKIE_MAX_AGE_SECONDS) {
  const secure = window.location.protocol === "https:" ? "; Secure" : "";
  return `; Path=/; Max-Age=${maxAge}; SameSite=Lax${secure}`;
}

function setCookie(name: string, value: string, maxAge = COOKIE_MAX_AGE_SECONDS) {
  if (!isBrowser()) return;
  document.cookie = `${name}=${encodeURIComponent(value)}${cookieAttributes(maxAge)}`;
}

function getCookie(name: string): string | null {
  if (!isBrowser()) return null;
  const prefix = `${name}=`;
  const found = document.cookie
    .split(";")
    .map((part) => part.trim())
    .find((part) => part.startsWith(prefix));
  if (!found) return null;
  try {
    return decodeURIComponent(found.slice(prefix.length));
  } catch {
    return null;
  }
}

function removeCookie(name: string) {
  if (!isBrowser()) return;
  document.cookie = `${name}=; Path=/; Max-Age=0; SameSite=Lax`;
}

function cookieKey(key: string) {
  return `${SUPABASE_COOKIE_PREFIX}${btoa(key).replace(/=+$/g, "")}`;
}

function safeLocalStorageGet(key: string) {
  try {
    return localStorage.getItem(key);
  } catch {
    return null;
  }
}

function safeLocalStorageSet(key: string, value: string) {
  try {
    localStorage.setItem(key, value);
  } catch {
    /* cookie fallback still persists the session */
  }
}

function safeLocalStorageRemove(key: string) {
  try {
    localStorage.removeItem(key);
  } catch {
    /* ignore */
  }
}

function createPersistentAuthStorage() {
  return {
    getItem(key: string) {
      return safeLocalStorageGet(key) ?? getCookie(cookieKey(key));
    },
    setItem(key: string, value: string) {
      safeLocalStorageSet(key, value);
      // Mirror Supabase's auth-token storage too. If a browser evicts localStorage,
      // the next boot can still recover the session from the cookie copy.
      setCookie(cookieKey(key), value);
    },
    removeItem(key: string) {
      safeLocalStorageRemove(key);
      removeCookie(cookieKey(key));
    },
  };
}

export function saveSessionBackup(session: SessionBackup) {
  if (!isBrowser()) return;
  safeLocalStorageSet(
    SESSION_BACKUP_KEY,
    JSON.stringify({
      access_token: session.access_token,
      refresh_token: session.refresh_token,
    }),
  );
  setCookie(SESSION_COOKIE_ACCESS, session.access_token);
  setCookie(SESSION_COOKIE_REFRESH, session.refresh_token);
}

export function clearSessionBackup() {
  if (!isBrowser()) return;
  safeLocalStorageRemove(SESSION_BACKUP_KEY);
  removeCookie(SESSION_COOKIE_ACCESS);
  removeCookie(SESSION_COOKIE_REFRESH);
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Add them to the Cloudflare deployment.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: isBrowser() ? createPersistentAuthStorage() : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: "pkce",
    },
  });

  client.auth.onAuthStateChange((event, session) => {
    if (session) saveSessionBackup(session);
    // Do not clear the backup on every SIGNED_OUT event. Browsers/Supabase can
    // emit this during transient refresh/storage failures, and wiping the
    // backup is what made users appear logged out repeatedly. Explicit logout
    // calls clearSessionBackup() before signOut().
    else if (event === "SIGNED_OUT") {
      console.info(
        "[DEADSET auth] signed-out event received; keeping backup unless user explicitly logged out",
      );
    }
  });

  return client;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

export async function restoreSupabaseSession() {
  if (!isBrowser()) return;
  const {
    data: { session },
  } = await supabase.auth.getSession();
  if (session) {
    saveSessionBackup(session);
    return;
  }
  const raw = safeLocalStorageGet(SESSION_BACKUP_KEY);
  const cookieBackup = {
    access_token: getCookie(SESSION_COOKIE_ACCESS),
    refresh_token: getCookie(SESSION_COOKIE_REFRESH),
  };
  try {
    const saved = raw ? (JSON.parse(raw) as Partial<SessionBackup>) : cookieBackup;
    if (!saved.access_token || !saved.refresh_token) throw new Error("Invalid session backup");
    const { error } = await supabase.auth.setSession({
      access_token: saved.access_token,
      refresh_token: saved.refresh_token,
    });
    if (!error) return;

    // If the access token is stale, recover using the long-lived refresh token.
    const { data: refreshed, error: refreshError } = await supabase.auth.refreshSession({
      refresh_token: saved.refresh_token,
    });
    if (refreshError) throw refreshError;
    if (refreshed.session) saveSessionBackup(refreshed.session);
  } catch {
    // Keep the backup. Some browsers briefly fail storage/network operations;
    // deleting the refresh token here causes the very logout loop we're trying
    // to prevent. Explicit logout still clears it.
  }
}
